before_script:
  - docker info
  - rvm install ruby-2.7
  - rvm use ruby-2.7
  - mkdir roles
  - ln -s . roles/zerotier
  - j2 default.yml.j2 -o default.yml
stages:
  - tests

kitchen-sink:
  stage: tests
  script:
    - bundle install
    - bundle exec kitchen test