before_script:
  - docker info
  - source $HOME/.rvm/scripts/rvm
  - rvm use ruby-2.7
  - mkdir -p roles/zerotier
  - mv defaults/ roles/zerotier/defaults
  - mv library/ roles/zerotier/library
  - mv tasks/ roles/zerotier/tasks
  - j2 default.yml.j2 -o default.yml
stages:
  - tests

kitchen-sink:
  stage: tests
  script:
    - bundle install
    - bundle exec kitchen test