before_script:
  - docker info
  - rvmsudo rvm get stable --auto-dotfiles
  - rvm fix-permissions system
  - rvm install ruby-2.7
stages:
  - tests

kitchen-sink:
  stage: tests
  script:
    - bundle install
