before_script:
  - docker info

stages:
  - tests

kitchen-sink:
  stage: tests
  script:
    - export GEM_HOME=/home/gitlab-runner/.gem
    - export PATH=/home/gitlab-runner/.gem/bin/:$PATH
    - source "/etc/profile.d/rvm.sh"
    - rvm install ruby-2.7
    - bundle install
