---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: ansible_playbook
  playbook: default.yml
  roles_path: roles

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:18.04

suites:
  - name: default