---
- name: Install Prerequisite Packages
  apt:
    update_cache: yes
    state: present
    pkg: "{{osmap['ubuntu'][ansible_distribution_release]['packages']}}"
- name: Add Zerotier GPG Key
  apt_key:
    url: "{{zerotier_repo['gpg']}}"
    state: present

- name: Add Zerotier Repo
  apt_repository:
    repo: "{{osmap['ubuntu'][ansible_distribution_release]['zerotier_deb_url']}}"

- name: Install ZeroTier
  apt:
    name: zerotier-one={{zerotier_version}}
    state: present
    update_cache: yes