---
- name: Install Prerequisite Packages
  apt:
    update_cache: yes
    state: present
    pkg:
      - gpg
- name: Add Zerotier GPG Key
  apt_key:
    url: "{{zerotier_repo['gpg']}}"
    state: present

- name: Add Zerotier Repo
  apt_repository:
    repo: "deb {{zerotier_repo['base_url_ubuntu']}}{{ansible_distribution_release}} {{ansible_distribution_release}} main"

- name: Install ZeroTier
  apt:
    name: zerotier-one={{zerotier_version}}
    state: present
    update_cache: yes