---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware_desktop
platforms:
  - name: test
    box: generic/ubuntu2004
provisioner:
  name: ansible
verifier:
  name: ansible
